### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by geopic** [Ghost---Shadow/word-highlighter#1]
Hey, I found your post on /r/javascript. Your library is cool but it lacks TypeScript support, would you like me to add it?

**Comment by Ghost---Shadow** [comment]
Typescript support? Does this already work on typescript?

I mean, as long as it doesnt break anything for javascript, I see no harm in that.

Please go ahead :)

**Comment by geopic** [comment]
> Typescript support? Does this already work on typescript?

Oh it does, but it just won't have type-checking included, it'll help a great deal for TS developers using this library since the type-checking feature of TS can actually be utilised. I'll get started on it now. :+1:
